# Generated by Django 3.2.5 on 2021-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210717_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='size_fluid_ounce',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_ml',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
